<?xml version="1.0" encoding="utf-8"?><Database Name="UCSF" Class="UCSDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=UCSF;Integrated Security=True" SettingsObjectName="UCSF.Data.Properties.Settings" SettingsPropertyName="UCSFConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.agGrant" Member="Grants">
    <Type Name="Grant">
      <Column Name="GrantPK" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ApplicationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Activity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AdministeringIC" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ApplicationType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ARRAFunded" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BudgetStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BudgetEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FOANumber" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FullProjectNum" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FundingICS" Type="System.String" DbType="VarChar(400)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="OrgCity" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrgCountry" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrgDistrict" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrgDUNS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="OrgDept" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrgFIPS" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrgState" Type="System.String" DbType="VarChar(2)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrgZip" Type="System.String" DbType="VarChar(9)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ICName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OrgName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ProjectTitle" Type="System.String" DbType="VarChar(255)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ProjectStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ProjectEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TotalCost" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CoreProjectNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="XML" Type="System.String" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsVerified" Storage="_IsVerfied" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Grant_GrantPrincipal" Member="GrantPrincipals" ThisKey="GrantPK" OtherKey="GrantPK" Type="GrantPrincipal" />
    </Type>
  </Table>
  <Table Name="dbo.agPrincipalInvestigator" Member="PrincipalInvestigators">
    <Type Name="PrincipalInvestigator">
      <Column Name="PrincipalInvestigatorPK" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PrincipalInvestigatorId" Storage="_PrincipalInvestigator_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="EmployeeId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="PrincipalInvestigator_GrantPrincipal" Member="GrantPrincipals" ThisKey="PrincipalInvestigatorPK" OtherKey="PrincipalInvestigatorPK" Type="GrantPrincipal" />
    </Type>
  </Table>
  <Table Name="dbo.agGrantFile" Member="GrantFiles">
    <Type Name="GrantFile">
      <Column Name="FilePK" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Processed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.agGrantPrincipal" Member="GrantPrincipals">
    <Type Name="GrantPrincipal">
      <Column Name="GrantPrincipalPK" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="GrantPK" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PrincipalInvestigatorPK" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Grant_GrantPrincipal" Member="Grant" ThisKey="GrantPK" OtherKey="GrantPK" Type="Grant" IsForeignKey="true" />
      <Association Name="PrincipalInvestigator_GrantPrincipal" Member="PrincipalInvestigator" ThisKey="PrincipalInvestigatorPK" OtherKey="PrincipalInvestigatorPK" Type="PrincipalInvestigator" IsForeignKey="true" />
    </Type>
  </Table>
</Database>