/****** Object:  Table [dbo].[FNO_IMPORT]    Script Date: 06/21/2011 14:59:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FNO_IMPORT](
                [INDIVIDUAL_ID] [varchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                [UID_USERID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
