#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatterDataLoader
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="profiles")]
	public partial class ProfilesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertperson(person instance);
    partial void Updateperson(person instance);
    partial void Deleteperson(person instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    #endregion
		
		public ProfilesDataContext() : 
				base(global::ChatterDataLoader.Properties.Settings.Default.profilesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProfilesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProfilesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProfilesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProfilesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<person> persons
		{
			get
			{
				return this.GetTable<person>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.person")]
	public partial class person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PersonID;
		
		private System.Nullable<int> _UserID;
		
		private System.Nullable<int> _CtscID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _MiddleName;
		
		private string _DisplayName;
		
		private string _DegreeList;
		
		private string _Suffix;
		
		private System.Nullable<bool> _IsActive;
		
		private string _EmailAddr;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _AddressLine1;
		
		private string _AddressLine2;
		
		private string _AddressLine3;
		
		private string _AddressLine4;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _Building;
		
		private System.Nullable<int> _Floor;
		
		private string _Room;
		
		private string _AddressString;
		
		private System.Nullable<decimal> _Latitude;
		
		private System.Nullable<decimal> _Longitude;
		
		private System.Nullable<byte> _GeoScore;
		
		private string _AssistantName;
		
		private string _AssistantPhone;
		
		private string _AssistantEmail;
		
		private string _AssistantAddress;
		
		private string _AssistantFax;
		
		private string _Title;
		
		private System.Nullable<int> _FacultyRankID;
		
		private string _JobCode;
		
		private string _InternalUsername;
		
		private string _InternalID;
		
		private string _InternalLDAPUserName;
		
		private System.Nullable<int> _InternalFacultyID;
		
		private string _InternalPersonType;
		
		private string _InternalFullPartTime;
		
		private string _InternalAdminTitle;
		
		private string _InternalDeptType;
		
		private System.Nullable<bool> _Visible;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonIDChanging(int value);
    partial void OnPersonIDChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    partial void OnCtscIDChanging(System.Nullable<int> value);
    partial void OnCtscIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnDegreeListChanging(string value);
    partial void OnDegreeListChanged();
    partial void OnSuffixChanging(string value);
    partial void OnSuffixChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnEmailAddrChanging(string value);
    partial void OnEmailAddrChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnAddressLine1Changing(string value);
    partial void OnAddressLine1Changed();
    partial void OnAddressLine2Changing(string value);
    partial void OnAddressLine2Changed();
    partial void OnAddressLine3Changing(string value);
    partial void OnAddressLine3Changed();
    partial void OnAddressLine4Changing(string value);
    partial void OnAddressLine4Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnBuildingChanging(string value);
    partial void OnBuildingChanged();
    partial void OnFloorChanging(System.Nullable<int> value);
    partial void OnFloorChanged();
    partial void OnRoomChanging(string value);
    partial void OnRoomChanged();
    partial void OnAddressStringChanging(string value);
    partial void OnAddressStringChanged();
    partial void OnLatitudeChanging(System.Nullable<decimal> value);
    partial void OnLatitudeChanged();
    partial void OnLongitudeChanging(System.Nullable<decimal> value);
    partial void OnLongitudeChanged();
    partial void OnGeoScoreChanging(System.Nullable<byte> value);
    partial void OnGeoScoreChanged();
    partial void OnAssistantNameChanging(string value);
    partial void OnAssistantNameChanged();
    partial void OnAssistantPhoneChanging(string value);
    partial void OnAssistantPhoneChanged();
    partial void OnAssistantEmailChanging(string value);
    partial void OnAssistantEmailChanged();
    partial void OnAssistantAddressChanging(string value);
    partial void OnAssistantAddressChanged();
    partial void OnAssistantFaxChanging(string value);
    partial void OnAssistantFaxChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnFacultyRankIDChanging(System.Nullable<int> value);
    partial void OnFacultyRankIDChanged();
    partial void OnJobCodeChanging(string value);
    partial void OnJobCodeChanged();
    partial void OnInternalUsernameChanging(string value);
    partial void OnInternalUsernameChanged();
    partial void OnInternalIDChanging(string value);
    partial void OnInternalIDChanged();
    partial void OnInternalLDAPUserNameChanging(string value);
    partial void OnInternalLDAPUserNameChanged();
    partial void OnInternalFacultyIDChanging(System.Nullable<int> value);
    partial void OnInternalFacultyIDChanged();
    partial void OnInternalPersonTypeChanging(string value);
    partial void OnInternalPersonTypeChanged();
    partial void OnInternalFullPartTimeChanging(string value);
    partial void OnInternalFullPartTimeChanged();
    partial void OnInternalAdminTitleChanging(string value);
    partial void OnInternalAdminTitleChanged();
    partial void OnInternalDeptTypeChanging(string value);
    partial void OnInternalDeptTypeChanged();
    partial void OnVisibleChanging(System.Nullable<bool> value);
    partial void OnVisibleChanged();
    #endregion
		
		public person()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				if ((this._PersonID != value))
				{
					this.OnPersonIDChanging(value);
					this.SendPropertyChanging();
					this._PersonID = value;
					this.SendPropertyChanged("PersonID");
					this.OnPersonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtscID", DbType="Int")]
		public System.Nullable<int> CtscID
		{
			get
			{
				return this._CtscID;
			}
			set
			{
				if ((this._CtscID != value))
				{
					this.OnCtscIDChanging(value);
					this.SendPropertyChanging();
					this._CtscID = value;
					this.SendPropertyChanged("CtscID");
					this.OnCtscIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(50)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(255)")]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DegreeList", DbType="NVarChar(50)")]
		public string DegreeList
		{
			get
			{
				return this._DegreeList;
			}
			set
			{
				if ((this._DegreeList != value))
				{
					this.OnDegreeListChanging(value);
					this.SendPropertyChanging();
					this._DegreeList = value;
					this.SendPropertyChanged("DegreeList");
					this.OnDegreeListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suffix", DbType="NVarChar(50)")]
		public string Suffix
		{
			get
			{
				return this._Suffix;
			}
			set
			{
				if ((this._Suffix != value))
				{
					this.OnSuffixChanging(value);
					this.SendPropertyChanging();
					this._Suffix = value;
					this.SendPropertyChanged("Suffix");
					this.OnSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddr", DbType="NVarChar(255)")]
		public string EmailAddr
		{
			get
			{
				return this._EmailAddr;
			}
			set
			{
				if ((this._EmailAddr != value))
				{
					this.OnEmailAddrChanging(value);
					this.SendPropertyChanging();
					this._EmailAddr = value;
					this.SendPropertyChanged("EmailAddr");
					this.OnEmailAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(35)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(25)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine1", DbType="NVarChar(55)")]
		public string AddressLine1
		{
			get
			{
				return this._AddressLine1;
			}
			set
			{
				if ((this._AddressLine1 != value))
				{
					this.OnAddressLine1Changing(value);
					this.SendPropertyChanging();
					this._AddressLine1 = value;
					this.SendPropertyChanged("AddressLine1");
					this.OnAddressLine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine2", DbType="NVarChar(55)")]
		public string AddressLine2
		{
			get
			{
				return this._AddressLine2;
			}
			set
			{
				if ((this._AddressLine2 != value))
				{
					this.OnAddressLine2Changing(value);
					this.SendPropertyChanging();
					this._AddressLine2 = value;
					this.SendPropertyChanged("AddressLine2");
					this.OnAddressLine2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine3", DbType="NVarChar(55)")]
		public string AddressLine3
		{
			get
			{
				return this._AddressLine3;
			}
			set
			{
				if ((this._AddressLine3 != value))
				{
					this.OnAddressLine3Changing(value);
					this.SendPropertyChanging();
					this._AddressLine3 = value;
					this.SendPropertyChanged("AddressLine3");
					this.OnAddressLine3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine4", DbType="NVarChar(55)")]
		public string AddressLine4
		{
			get
			{
				return this._AddressLine4;
			}
			set
			{
				if ((this._AddressLine4 != value))
				{
					this.OnAddressLine4Changing(value);
					this.SendPropertyChanging();
					this._AddressLine4 = value;
					this.SendPropertyChanged("AddressLine4");
					this.OnAddressLine4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(2)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(10)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Building", DbType="NVarChar(255)")]
		public string Building
		{
			get
			{
				return this._Building;
			}
			set
			{
				if ((this._Building != value))
				{
					this.OnBuildingChanging(value);
					this.SendPropertyChanging();
					this._Building = value;
					this.SendPropertyChanged("Building");
					this.OnBuildingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Floor", DbType="Int")]
		public System.Nullable<int> Floor
		{
			get
			{
				return this._Floor;
			}
			set
			{
				if ((this._Floor != value))
				{
					this.OnFloorChanging(value);
					this.SendPropertyChanging();
					this._Floor = value;
					this.SendPropertyChanged("Floor");
					this.OnFloorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room", DbType="NVarChar(255)")]
		public string Room
		{
			get
			{
				return this._Room;
			}
			set
			{
				if ((this._Room != value))
				{
					this.OnRoomChanging(value);
					this.SendPropertyChanging();
					this._Room = value;
					this.SendPropertyChanged("Room");
					this.OnRoomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressString", DbType="NVarChar(1000)")]
		public string AddressString
		{
			get
			{
				return this._AddressString;
			}
			set
			{
				if ((this._AddressString != value))
				{
					this.OnAddressStringChanging(value);
					this.SendPropertyChanging();
					this._AddressString = value;
					this.SendPropertyChanged("AddressString");
					this.OnAddressStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(18,14)")]
		public System.Nullable<decimal> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(18,14)")]
		public System.Nullable<decimal> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeoScore", DbType="TinyInt")]
		public System.Nullable<byte> GeoScore
		{
			get
			{
				return this._GeoScore;
			}
			set
			{
				if ((this._GeoScore != value))
				{
					this.OnGeoScoreChanging(value);
					this.SendPropertyChanging();
					this._GeoScore = value;
					this.SendPropertyChanged("GeoScore");
					this.OnGeoScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssistantName", DbType="NVarChar(255)")]
		public string AssistantName
		{
			get
			{
				return this._AssistantName;
			}
			set
			{
				if ((this._AssistantName != value))
				{
					this.OnAssistantNameChanging(value);
					this.SendPropertyChanging();
					this._AssistantName = value;
					this.SendPropertyChanged("AssistantName");
					this.OnAssistantNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssistantPhone", DbType="NVarChar(35)")]
		public string AssistantPhone
		{
			get
			{
				return this._AssistantPhone;
			}
			set
			{
				if ((this._AssistantPhone != value))
				{
					this.OnAssistantPhoneChanging(value);
					this.SendPropertyChanging();
					this._AssistantPhone = value;
					this.SendPropertyChanged("AssistantPhone");
					this.OnAssistantPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssistantEmail", DbType="NVarChar(255)")]
		public string AssistantEmail
		{
			get
			{
				return this._AssistantEmail;
			}
			set
			{
				if ((this._AssistantEmail != value))
				{
					this.OnAssistantEmailChanging(value);
					this.SendPropertyChanging();
					this._AssistantEmail = value;
					this.SendPropertyChanged("AssistantEmail");
					this.OnAssistantEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssistantAddress", DbType="NVarChar(1000)")]
		public string AssistantAddress
		{
			get
			{
				return this._AssistantAddress;
			}
			set
			{
				if ((this._AssistantAddress != value))
				{
					this.OnAssistantAddressChanging(value);
					this.SendPropertyChanging();
					this._AssistantAddress = value;
					this.SendPropertyChanged("AssistantAddress");
					this.OnAssistantAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssistantFax", DbType="NVarChar(25)")]
		public string AssistantFax
		{
			get
			{
				return this._AssistantFax;
			}
			set
			{
				if ((this._AssistantFax != value))
				{
					this.OnAssistantFaxChanging(value);
					this.SendPropertyChanging();
					this._AssistantFax = value;
					this.SendPropertyChanged("AssistantFax");
					this.OnAssistantFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(255)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacultyRankID", DbType="Int")]
		public System.Nullable<int> FacultyRankID
		{
			get
			{
				return this._FacultyRankID;
			}
			set
			{
				if ((this._FacultyRankID != value))
				{
					this.OnFacultyRankIDChanging(value);
					this.SendPropertyChanging();
					this._FacultyRankID = value;
					this.SendPropertyChanged("FacultyRankID");
					this.OnFacultyRankIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobCode", DbType="VarChar(50)")]
		public string JobCode
		{
			get
			{
				return this._JobCode;
			}
			set
			{
				if ((this._JobCode != value))
				{
					this.OnJobCodeChanging(value);
					this.SendPropertyChanging();
					this._JobCode = value;
					this.SendPropertyChanged("JobCode");
					this.OnJobCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalUsername", DbType="NVarChar(50)")]
		public string InternalUsername
		{
			get
			{
				return this._InternalUsername;
			}
			set
			{
				if ((this._InternalUsername != value))
				{
					this.OnInternalUsernameChanging(value);
					this.SendPropertyChanging();
					this._InternalUsername = value;
					this.SendPropertyChanged("InternalUsername");
					this.OnInternalUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalID", DbType="NVarChar(50)")]
		public string InternalID
		{
			get
			{
				return this._InternalID;
			}
			set
			{
				if ((this._InternalID != value))
				{
					this.OnInternalIDChanging(value);
					this.SendPropertyChanging();
					this._InternalID = value;
					this.SendPropertyChanged("InternalID");
					this.OnInternalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalLDAPUserName", DbType="NVarChar(50)")]
		public string InternalLDAPUserName
		{
			get
			{
				return this._InternalLDAPUserName;
			}
			set
			{
				if ((this._InternalLDAPUserName != value))
				{
					this.OnInternalLDAPUserNameChanging(value);
					this.SendPropertyChanging();
					this._InternalLDAPUserName = value;
					this.SendPropertyChanged("InternalLDAPUserName");
					this.OnInternalLDAPUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalFacultyID", DbType="Int")]
		public System.Nullable<int> InternalFacultyID
		{
			get
			{
				return this._InternalFacultyID;
			}
			set
			{
				if ((this._InternalFacultyID != value))
				{
					this.OnInternalFacultyIDChanging(value);
					this.SendPropertyChanging();
					this._InternalFacultyID = value;
					this.SendPropertyChanged("InternalFacultyID");
					this.OnInternalFacultyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalPersonType", DbType="VarChar(50)")]
		public string InternalPersonType
		{
			get
			{
				return this._InternalPersonType;
			}
			set
			{
				if ((this._InternalPersonType != value))
				{
					this.OnInternalPersonTypeChanging(value);
					this.SendPropertyChanging();
					this._InternalPersonType = value;
					this.SendPropertyChanged("InternalPersonType");
					this.OnInternalPersonTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalFullPartTime", DbType="NVarChar(50)")]
		public string InternalFullPartTime
		{
			get
			{
				return this._InternalFullPartTime;
			}
			set
			{
				if ((this._InternalFullPartTime != value))
				{
					this.OnInternalFullPartTimeChanging(value);
					this.SendPropertyChanging();
					this._InternalFullPartTime = value;
					this.SendPropertyChanged("InternalFullPartTime");
					this.OnInternalFullPartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalAdminTitle", DbType="NVarChar(200)")]
		public string InternalAdminTitle
		{
			get
			{
				return this._InternalAdminTitle;
			}
			set
			{
				if ((this._InternalAdminTitle != value))
				{
					this.OnInternalAdminTitleChanging(value);
					this.SendPropertyChanging();
					this._InternalAdminTitle = value;
					this.SendPropertyChanged("InternalAdminTitle");
					this.OnInternalAdminTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalDeptType", DbType="VarChar(50)")]
		public string InternalDeptType
		{
			get
			{
				return this._InternalDeptType;
			}
			set
			{
				if ((this._InternalDeptType != value))
				{
					this.OnInternalDeptTypeChanging(value);
					this.SendPropertyChanging();
					this._InternalDeptType = value;
					this.SendPropertyChanged("InternalDeptType");
					this.OnInternalDeptTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visible", DbType="Bit")]
		public System.Nullable<bool> Visible
		{
			get
			{
				return this._Visible;
			}
			set
			{
				if ((this._Visible != value))
				{
					this.OnVisibleChanging(value);
					this.SendPropertyChanging();
					this._Visible = value;
					this.SendPropertyChanged("Visible");
					this.OnVisibleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private System.Nullable<int> _PersonID;
		
		private System.Nullable<int> _CtscID;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _CanBeProxy;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _DisplayName;
		
		private string _OfficePhone;
		
		private string _EmailAddr;
		
		private string _InstitutionFullname;
		
		private string _DepartmentFullname;
		
		private string _DivisionFullname;
		
		private string _UserName;
		
		private string _Password;
		
		private System.Nullable<int> _PasswordFormat;
		
		private string _PasswordQuestion;
		
		private string _PasswordAnswer;
		
		private System.Nullable<System.DateTime> _LastActivityDate;
		
		private System.Nullable<System.DateTime> _LastLoginDate;
		
		private System.Nullable<System.DateTime> _LastPasswordChangedDate;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<bool> _IsLockedOut;
		
		private System.Nullable<System.DateTime> _LastLockOutDate;
		
		private System.Nullable<int> _FailedPasswordAttemptCount;
		
		private System.Nullable<System.DateTime> _FailedPasswordAttemptWindowStart;
		
		private System.Nullable<int> _FailedPasswordAnswerAttemptCount;
		
		private System.Nullable<System.DateTime> _FailedPasswordAnswerAttemptWindowstart;
		
		private string _ApplicationName;
		
		private string _Comment;
		
		private System.Nullable<bool> _IsApproved;
		
		private System.Nullable<bool> _IsOnline;
		
		private string _InternalLdapUsername;
		
		private System.Nullable<int> _InternalFacultyID;
		
		private string _InternalUserName;
		
		private string _InternalID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnPersonIDChanging(System.Nullable<int> value);
    partial void OnPersonIDChanged();
    partial void OnCtscIDChanging(System.Nullable<int> value);
    partial void OnCtscIDChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnCanBeProxyChanging(System.Nullable<bool> value);
    partial void OnCanBeProxyChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnOfficePhoneChanging(string value);
    partial void OnOfficePhoneChanged();
    partial void OnEmailAddrChanging(string value);
    partial void OnEmailAddrChanged();
    partial void OnInstitutionFullnameChanging(string value);
    partial void OnInstitutionFullnameChanged();
    partial void OnDepartmentFullnameChanging(string value);
    partial void OnDepartmentFullnameChanged();
    partial void OnDivisionFullnameChanging(string value);
    partial void OnDivisionFullnameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPasswordFormatChanging(System.Nullable<int> value);
    partial void OnPasswordFormatChanged();
    partial void OnPasswordQuestionChanging(string value);
    partial void OnPasswordQuestionChanged();
    partial void OnPasswordAnswerChanging(string value);
    partial void OnPasswordAnswerChanged();
    partial void OnLastActivityDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastActivityDateChanged();
    partial void OnLastLoginDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginDateChanged();
    partial void OnLastPasswordChangedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastPasswordChangedDateChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnIsLockedOutChanging(System.Nullable<bool> value);
    partial void OnIsLockedOutChanged();
    partial void OnLastLockOutDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLockOutDateChanged();
    partial void OnFailedPasswordAttemptCountChanging(System.Nullable<int> value);
    partial void OnFailedPasswordAttemptCountChanged();
    partial void OnFailedPasswordAttemptWindowStartChanging(System.Nullable<System.DateTime> value);
    partial void OnFailedPasswordAttemptWindowStartChanged();
    partial void OnFailedPasswordAnswerAttemptCountChanging(System.Nullable<int> value);
    partial void OnFailedPasswordAnswerAttemptCountChanged();
    partial void OnFailedPasswordAnswerAttemptWindowstartChanging(System.Nullable<System.DateTime> value);
    partial void OnFailedPasswordAnswerAttemptWindowstartChanged();
    partial void OnApplicationNameChanging(string value);
    partial void OnApplicationNameChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnIsApprovedChanging(System.Nullable<bool> value);
    partial void OnIsApprovedChanged();
    partial void OnIsOnlineChanging(System.Nullable<bool> value);
    partial void OnIsOnlineChanged();
    partial void OnInternalLdapUsernameChanging(string value);
    partial void OnInternalLdapUsernameChanged();
    partial void OnInternalFacultyIDChanging(System.Nullable<int> value);
    partial void OnInternalFacultyIDChanged();
    partial void OnInternalUserNameChanging(string value);
    partial void OnInternalUserNameChanged();
    partial void OnInternalIDChanging(string value);
    partial void OnInternalIDChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonID", DbType="Int")]
		public System.Nullable<int> PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				if ((this._PersonID != value))
				{
					this.OnPersonIDChanging(value);
					this.SendPropertyChanging();
					this._PersonID = value;
					this.SendPropertyChanged("PersonID");
					this.OnPersonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtscID", DbType="Int")]
		public System.Nullable<int> CtscID
		{
			get
			{
				return this._CtscID;
			}
			set
			{
				if ((this._CtscID != value))
				{
					this.OnCtscIDChanging(value);
					this.SendPropertyChanging();
					this._CtscID = value;
					this.SendPropertyChanged("CtscID");
					this.OnCtscIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanBeProxy", DbType="Bit")]
		public System.Nullable<bool> CanBeProxy
		{
			get
			{
				return this._CanBeProxy;
			}
			set
			{
				if ((this._CanBeProxy != value))
				{
					this.OnCanBeProxyChanging(value);
					this.SendPropertyChanging();
					this._CanBeProxy = value;
					this.SendPropertyChanged("CanBeProxy");
					this.OnCanBeProxyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(100)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(100)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(255)")]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficePhone", DbType="VarChar(35)")]
		public string OfficePhone
		{
			get
			{
				return this._OfficePhone;
			}
			set
			{
				if ((this._OfficePhone != value))
				{
					this.OnOfficePhoneChanging(value);
					this.SendPropertyChanging();
					this._OfficePhone = value;
					this.SendPropertyChanged("OfficePhone");
					this.OnOfficePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddr", DbType="NVarChar(255)")]
		public string EmailAddr
		{
			get
			{
				return this._EmailAddr;
			}
			set
			{
				if ((this._EmailAddr != value))
				{
					this.OnEmailAddrChanging(value);
					this.SendPropertyChanging();
					this._EmailAddr = value;
					this.SendPropertyChanged("EmailAddr");
					this.OnEmailAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstitutionFullname", DbType="NVarChar(500)")]
		public string InstitutionFullname
		{
			get
			{
				return this._InstitutionFullname;
			}
			set
			{
				if ((this._InstitutionFullname != value))
				{
					this.OnInstitutionFullnameChanging(value);
					this.SendPropertyChanging();
					this._InstitutionFullname = value;
					this.SendPropertyChanged("InstitutionFullname");
					this.OnInstitutionFullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentFullname", DbType="NVarChar(500)")]
		public string DepartmentFullname
		{
			get
			{
				return this._DepartmentFullname;
			}
			set
			{
				if ((this._DepartmentFullname != value))
				{
					this.OnDepartmentFullnameChanging(value);
					this.SendPropertyChanging();
					this._DepartmentFullname = value;
					this.SendPropertyChanged("DepartmentFullname");
					this.OnDepartmentFullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionFullname", DbType="NVarChar(500)")]
		public string DivisionFullname
		{
			get
			{
				return this._DivisionFullname;
			}
			set
			{
				if ((this._DivisionFullname != value))
				{
					this.OnDivisionFullnameChanging(value);
					this.SendPropertyChanging();
					this._DivisionFullname = value;
					this.SendPropertyChanged("DivisionFullname");
					this.OnDivisionFullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(128)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordFormat", DbType="Int")]
		public System.Nullable<int> PasswordFormat
		{
			get
			{
				return this._PasswordFormat;
			}
			set
			{
				if ((this._PasswordFormat != value))
				{
					this.OnPasswordFormatChanging(value);
					this.SendPropertyChanging();
					this._PasswordFormat = value;
					this.SendPropertyChanged("PasswordFormat");
					this.OnPasswordFormatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordQuestion", DbType="VarChar(255)")]
		public string PasswordQuestion
		{
			get
			{
				return this._PasswordQuestion;
			}
			set
			{
				if ((this._PasswordQuestion != value))
				{
					this.OnPasswordQuestionChanging(value);
					this.SendPropertyChanging();
					this._PasswordQuestion = value;
					this.SendPropertyChanged("PasswordQuestion");
					this.OnPasswordQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordAnswer", DbType="VarChar(255)")]
		public string PasswordAnswer
		{
			get
			{
				return this._PasswordAnswer;
			}
			set
			{
				if ((this._PasswordAnswer != value))
				{
					this.OnPasswordAnswerChanging(value);
					this.SendPropertyChanging();
					this._PasswordAnswer = value;
					this.SendPropertyChanged("PasswordAnswer");
					this.OnPasswordAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastActivityDate
		{
			get
			{
				return this._LastActivityDate;
			}
			set
			{
				if ((this._LastActivityDate != value))
				{
					this.OnLastActivityDateChanging(value);
					this.SendPropertyChanging();
					this._LastActivityDate = value;
					this.SendPropertyChanged("LastActivityDate");
					this.OnLastActivityDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLoginDate
		{
			get
			{
				return this._LastLoginDate;
			}
			set
			{
				if ((this._LastLoginDate != value))
				{
					this.OnLastLoginDateChanging(value);
					this.SendPropertyChanging();
					this._LastLoginDate = value;
					this.SendPropertyChanged("LastLoginDate");
					this.OnLastLoginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPasswordChangedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastPasswordChangedDate
		{
			get
			{
				return this._LastPasswordChangedDate;
			}
			set
			{
				if ((this._LastPasswordChangedDate != value))
				{
					this.OnLastPasswordChangedDateChanging(value);
					this.SendPropertyChanging();
					this._LastPasswordChangedDate = value;
					this.SendPropertyChanged("LastPasswordChangedDate");
					this.OnLastPasswordChangedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLockedOut", DbType="Bit")]
		public System.Nullable<bool> IsLockedOut
		{
			get
			{
				return this._IsLockedOut;
			}
			set
			{
				if ((this._IsLockedOut != value))
				{
					this.OnIsLockedOutChanging(value);
					this.SendPropertyChanging();
					this._IsLockedOut = value;
					this.SendPropertyChanged("IsLockedOut");
					this.OnIsLockedOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLockOutDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLockOutDate
		{
			get
			{
				return this._LastLockOutDate;
			}
			set
			{
				if ((this._LastLockOutDate != value))
				{
					this.OnLastLockOutDateChanging(value);
					this.SendPropertyChanging();
					this._LastLockOutDate = value;
					this.SendPropertyChanged("LastLockOutDate");
					this.OnLastLockOutDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAttemptCount", DbType="Int")]
		public System.Nullable<int> FailedPasswordAttemptCount
		{
			get
			{
				return this._FailedPasswordAttemptCount;
			}
			set
			{
				if ((this._FailedPasswordAttemptCount != value))
				{
					this.OnFailedPasswordAttemptCountChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAttemptCount = value;
					this.SendPropertyChanged("FailedPasswordAttemptCount");
					this.OnFailedPasswordAttemptCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAttemptWindowStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> FailedPasswordAttemptWindowStart
		{
			get
			{
				return this._FailedPasswordAttemptWindowStart;
			}
			set
			{
				if ((this._FailedPasswordAttemptWindowStart != value))
				{
					this.OnFailedPasswordAttemptWindowStartChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAttemptWindowStart = value;
					this.SendPropertyChanged("FailedPasswordAttemptWindowStart");
					this.OnFailedPasswordAttemptWindowStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAnswerAttemptCount", DbType="Int")]
		public System.Nullable<int> FailedPasswordAnswerAttemptCount
		{
			get
			{
				return this._FailedPasswordAnswerAttemptCount;
			}
			set
			{
				if ((this._FailedPasswordAnswerAttemptCount != value))
				{
					this.OnFailedPasswordAnswerAttemptCountChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAnswerAttemptCount = value;
					this.SendPropertyChanged("FailedPasswordAnswerAttemptCount");
					this.OnFailedPasswordAnswerAttemptCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAnswerAttemptWindowstart", DbType="DateTime")]
		public System.Nullable<System.DateTime> FailedPasswordAnswerAttemptWindowstart
		{
			get
			{
				return this._FailedPasswordAnswerAttemptWindowstart;
			}
			set
			{
				if ((this._FailedPasswordAnswerAttemptWindowstart != value))
				{
					this.OnFailedPasswordAnswerAttemptWindowstartChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAnswerAttemptWindowstart = value;
					this.SendPropertyChanged("FailedPasswordAnswerAttemptWindowstart");
					this.OnFailedPasswordAnswerAttemptWindowstartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationName", DbType="VarChar(255)")]
		public string ApplicationName
		{
			get
			{
				return this._ApplicationName;
			}
			set
			{
				if ((this._ApplicationName != value))
				{
					this.OnApplicationNameChanging(value);
					this.SendPropertyChanging();
					this._ApplicationName = value;
					this.SendPropertyChanged("ApplicationName");
					this.OnApplicationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsApproved", DbType="Bit")]
		public System.Nullable<bool> IsApproved
		{
			get
			{
				return this._IsApproved;
			}
			set
			{
				if ((this._IsApproved != value))
				{
					this.OnIsApprovedChanging(value);
					this.SendPropertyChanging();
					this._IsApproved = value;
					this.SendPropertyChanged("IsApproved");
					this.OnIsApprovedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOnline", DbType="Bit")]
		public System.Nullable<bool> IsOnline
		{
			get
			{
				return this._IsOnline;
			}
			set
			{
				if ((this._IsOnline != value))
				{
					this.OnIsOnlineChanging(value);
					this.SendPropertyChanging();
					this._IsOnline = value;
					this.SendPropertyChanged("IsOnline");
					this.OnIsOnlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalLdapUsername", DbType="NVarChar(10)")]
		public string InternalLdapUsername
		{
			get
			{
				return this._InternalLdapUsername;
			}
			set
			{
				if ((this._InternalLdapUsername != value))
				{
					this.OnInternalLdapUsernameChanging(value);
					this.SendPropertyChanging();
					this._InternalLdapUsername = value;
					this.SendPropertyChanged("InternalLdapUsername");
					this.OnInternalLdapUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalFacultyID", DbType="Int")]
		public System.Nullable<int> InternalFacultyID
		{
			get
			{
				return this._InternalFacultyID;
			}
			set
			{
				if ((this._InternalFacultyID != value))
				{
					this.OnInternalFacultyIDChanging(value);
					this.SendPropertyChanging();
					this._InternalFacultyID = value;
					this.SendPropertyChanged("InternalFacultyID");
					this.OnInternalFacultyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalUserName", DbType="NVarChar(50)")]
		public string InternalUserName
		{
			get
			{
				return this._InternalUserName;
			}
			set
			{
				if ((this._InternalUserName != value))
				{
					this.OnInternalUserNameChanging(value);
					this.SendPropertyChanging();
					this._InternalUserName = value;
					this.SendPropertyChanged("InternalUserName");
					this.OnInternalUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalID", DbType="NVarChar(10)")]
		public string InternalID
		{
			get
			{
				return this._InternalID;
			}
			set
			{
				if ((this._InternalID != value))
				{
					this.OnInternalIDChanging(value);
					this.SendPropertyChanging();
					this._InternalID = value;
					this.SendPropertyChanged("InternalID");
					this.OnInternalIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
