<?xml version="1.0" encoding="utf-8"?>
<Database Name="profiles" Class="ProfilesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ALDAN;Initial Catalog=profiles;Persist Security Info=True;User ID=profiles" SettingsObjectName="ChatterService.Properties.Settings" SettingsPropertyName="profilesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.person" Member="persons">
    <Type Name="person">
      <Column Name="PersonID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CtscID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DegreeList" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Suffix" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EmailAddr" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="AddressLine1" Type="System.String" DbType="NVarChar(55)" CanBeNull="true" />
      <Column Name="AddressLine2" Type="System.String" DbType="NVarChar(55)" CanBeNull="true" />
      <Column Name="AddressLine3" Type="System.String" DbType="NVarChar(55)" CanBeNull="true" />
      <Column Name="AddressLine4" Type="System.String" DbType="NVarChar(55)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Building" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Floor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Room" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AddressString" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(18,14)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(18,14)" CanBeNull="true" />
      <Column Name="GeoScore" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="AssistantName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AssistantPhone" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="AssistantEmail" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AssistantAddress" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="AssistantFax" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FacultyRankID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JobCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InternalUsername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InternalID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InternalLDAPUserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InternalFacultyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InternalPersonType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InternalFullPartTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InternalAdminTitle" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="InternalDeptType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>